### ISSUE TITLE
linebeacon doesn't wrok well

### ISSUE THREAD

**Issue by taisei-m** [pizayanz/pxt-linebeacon#3]
I try to use microbit as linebeacon but I coudn't solve error 030. 
the error occured when doing the　method"linebeacon.startWithDeviceMessage() "
 I tried flashing a different hex file to my device and then  run  program again but it wouldn't work well.

`input.onButtonPressed(Button.A, function () {
    linebeacon.startWithDeviceMessage(
    "012c669b82",
    "1a2b3c4d5e6f70809010a0b0c0"
    )
})
input.onButtonPressed(Button.B, function () {
    linebeacon.stop()
})
`

**Comment by hisayan** [comment]
The problem was fixed.
regards.
