### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [pizayanz/pxt-linebeacon#4]
Hi @pizayanz,

As you might have seen from https://github.com/microsoft/pxt-microbit/issues/3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer. 

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit [here](https://github.com/lancaster-university/codal-microbit-v2/issues/31).

Looking at your extension source I believe that your extension falls under this category:

> Use of the mbed Bluetooth APIs

**Comment by hisayan** [comment]
Thanks.
I fixed the problem. What should I do next?

**Comment by microbit-mark** [comment]
@hisayan  This will need to be re-enabled in PXT with the latest release as the minimum version https://github.com/microsoft/pxt-microbit/blob/master/targetconfig.json#L217. I will make the Pull Request.

**Comment by microbit-pauline** [comment]
@microbit-mark - Can we now close this ticket?

**Comment by microbit-mark** [comment]
@hisayan can you please close the ticket?

**Comment by hisayan** [comment]
Thank you everyone
